# Generated by Django 5.2 on 2025-05-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refilling_air_conditioners', '0002_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Опция услуги'),
        ),
    ]
